id: A75D18EFE
base_file: f512F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:30:46.880405
  last_modified_at: 2022-05-31 05:30:46.880412
